const router = require('express').Router()
  const biometric = require('./biometric')
const category = require('./category')
const identification = require('./identification')
const users = require('./users')
const login = require('./login')
const Dashopord = require('./dashopord')
const images = require('./Images')
const img = require('./imgBinary')
const biometricFiles = require('./biometricFiles')
const sms_gateway = require('./sms_gateway')
const receptionRecord = require('./receptionRecord')
const province=require('./province')
const distinationtransform=require('./distinationtransform')
const receptionDepartment=require('./receptionDepartment')

//route
 router.use('/biometric', biometric)
router.use('/category', category)
router.use('/identification', identification)
 router.use('/province', province)
 router.use('/users', users)
router.use('/login', login)
 router.use('/dashpoard', Dashopord)
 router.use('/images', img)
router.use('/files', biometricFiles)
  router.use('/sendsms', sms_gateway)
router.use('/receptionRecord', receptionRecord)
router.use('/province', province)
router.use('/distinationtransform', distinationtransform)
router.use('/receptionDepartment', receptionDepartment)


module.exports = router